# Generated by Django 5.1.6 on 2025-04-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_walletbalance_alter_ethprice_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletbalance',
            name='wallet_address',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
