# Generated by Django 5.1.6 on 2025-04-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_walletbalance_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletbalance',
            name='eth_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='wallet_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='eth_balance',
            field=models.FloatField(max_length=40),
        ),
    ]
