# Generated by Django 5.1.6 on 2025-04-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_walletbalance_eth_price_walletbalance_wallet_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletbalance',
            name='wallet_address',
        ),
    ]
