# Generated by Django 5.1.6 on 2025-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_walletbalance_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbalance',
            name='eth_balance',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='eth_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='wallet_value',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
